pluginManagement {
  repositories {
    mavenCentral()
    gradlePluginPortal()
    maven { url "https://mirrors.tencent.com/nexus/repository/maven-tencent" }
    maven { url "https://mirrors.tencent.com/nexus/repository/maven-public" }
    mavenLocal()
  }
}

dependencyResolutionManagement {
  repositories {
    mavenCentral()
    google()
    maven { url "https://mirrors.tencent.com/nexus/repository/maven-tencent" }
    maven { url "https://mirrors.tencent.com/nexus/repository/maven-public" }
    mavenLocal()
  }

  versionCatalogs {
    libs {
      from(files("../gradle/libs.versions.toml"))
    }
  }
}

rootProject.name = "buildLogic"

include(":multiplatform-convention")
include(":toolchain-convention")
